defaults:
  - _self_
  - task: pick_place_d405

name: ghost_policy

policy:
  _target_: ghost_policy.GHOSTPolicy
  shape_meta: ${task.shape_meta}
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
    beta_schedule: 'squaredcos_cap_v2'
    clip_sample: True
    prediction_type: 'epsilon'

  horizon: 16
  n_action_steps: 8
  n_obs_steps: 2
  num_inference_steps: 100
  obs_as_global_cond: True
  diffusion_step_embed_dim: 256
  down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8
  condition_type: "film"
  
  # GHOST Specific
  use_pc_color: True
  use_aux_points: True
  pointnet_type: "pointnet"
  aux_point_num: 200 # 每个末端生成的点数
  aux_length: 0.2 # 激光束长度 (中间长柱)
  aux_trident_side_len: 0.1 # 两侧短柱长度
  aux_trident_max_width: 0.08 # 最大开合对应的物理宽度
  aux_radius: 0.01 # 圆柱半径
  
  # PointNet Config
  pointcloud_encoder_cfg:
    out_channels: 256
    use_layernorm: True
    final_norm: 'layernorm'

ema:
  _target_: diffusion_policy_3d.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 256
  num_workers: 8
  shuffle: True
  pin_memory: True
  persistent_workers: False

val_dataloader:
  batch_size: 256
  num_workers: 8
  shuffle: False
  pin_memory: True
  persistent_workers: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  # optimization
  lr_scheduler: "cosine"
  lr_warmup_steps: 500
  num_epochs: 1500
  gradient_accumulate_every: 1
  use_ema: True
  rollout_every: 200
  checkpoint_every: 200
  val_every: 50
  sample_every: 50
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0
  # saving
  output_dir: "data/outputs/${name}/${task.name}"

logging:
  group: ${name}
  id: null
  mode: online
  name: ${now:%H.%M.%S}_${name}_${task.name}_${policy.pointnet_type}
  project: ghost_policy
  resume: true
  tags:
  - ghost

checkpoint:
  save_ckpt: True
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 1
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%H.%M.%S}_${name}_${task.name}_${task.dataset_type}_${policy.pointnet_type}
  sweep:
    dir: data/outputs/${now:%H.%M.%S}_${name}_${task.name}_${task.dataset_type}_${policy.pointnet_type}
    subdir: ${hydra.job.num}

